### PR TITLE
fix: upgrade standard, and a few other dependencies. fix standard nits

### PR DESCRIPTION
**Pull request by bcoe**

### CODE REVIEW

**Comment by sc0ttyd** [comment]
:apologetic bump: Sorry to be a pain but any chance someone could look at merging this? I need the package.json update of istanbul-lib-source-maps to be released to fix a build issue.

**Comment by JaKXz** [comment]
@sc0ttyd if it's urgent you can just `npm i nyc#upgrade-standard` I believe. @bcoe just curious, is anything blocking this? it LGTM since it's pretty minor?

**Comment by bcoe** [comment]
@sc0ttyd @JaKXz could you give the release candidate a spin:

`npm cache clear; npm i nyc@next`

@sc0ttyd should have these updates you need, and I'd love to have some people test it because it has some fancy new features via @addaleax.

**Comment by sc0ttyd** [comment]
@bcoe sure, I'll give it a whirl on Monday when I've access to TC.

**Pull request merged**
