### PR TITLE
fix: upgrade to newer versions of source-map, signal-exit, and instrument

### PR DESCRIPTION
**Pull request by bcoe**
a few somewhat frightening dependencies being upgraded, we should test thoroughly.

@mourner mind taking this for a spin, it's what actually lands your performance fixes (along with some performance fixes I snuck into #388, yargs should now execute much less frequently).

### CODE REVIEW

**Comment by mourner** [comment]
@bcoe I'll try this out, thanks!

**Comment by mourner** [comment]
@bcoe this branch works great for me.

**Comment by bcoe** [comment]
@mourner seeing any significant performance gains, vs. `latest`?

**Comment by mourner** [comment]
@bcoe seeing the same performance gains I described in https://github.com/istanbuljs/istanbul-lib-instrument/pull/22

**Comment by bcoe** [comment]
@mourner cool, was curious if spawning yargs less frequently (which I believe has a 100ms overhead) would improve performance further -- this would specifically target people using `nyc` for instrumentation, rather than `babel-plugin-istanbul`.

**Comment by mourner** [comment]
@bcoe it probably shaved off a few hundred ms, but it's not really noticeable with a test suite that runs for 6+ minutes. :)

**Pull request merged**
