### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by coreyfarrell**
This is related to istanbuljs/istanbuljs#180 and was tested against that.

### CODE REVIEW

**Comment by coreyfarrell** [comment]
This did not have an error when testing within the istanbuljs monorepo, I think the failure is due to testing against the latest `@next` npm modules instead of testing against the pull request.

**Comment by coreyfarrell** [comment]
@bcoe I'm not sure what it takes to publish new `next` versions of `istanbuljs` monorepo, this PR is on hold for that (it needs those changes to pass tests).  I believe it's the change from micromatch to minimatch which changes the number of modules loaded.

**Comment by bcoe** [comment]
@coreyfarrell I've released new next versions of the istanbul mono repo.

**Comment by coreyfarrell** [comment]
@bcoe I thought you were going to bump istanbul-lib-hook to 2.0 since it has the a breaking API change?  I've still updated the PR so this should soon pass CI.

**Comment by bcoe** [comment]
@coreyfarrell see https://github.com/istanbuljs/istanbuljs/pull/181, I will release shortly.

**Comment by bcoe** [comment]
@coreyfarrell I have released `istanbul-lib-hook` at `2.x`.

**Pull request merged**
