### PR TITLE
test: stop using LAZY_LOAD_COUNT

### PR DESCRIPTION
**Pull request by bcoe**
remove fragile dependency on `LAZY_LOAD_COUNT` magic number.

### CODE REVIEW

**Comment by coreyfarrell** [comment]
@bcoe would you mind splitting this?  I'd prefer the first commit be merged on it's own, the CI changes separate.

**Comment by JaKXz** [comment]
Yeah your first commit passed, let's just merge that for now?

**Comment by bcoe** [comment]
@JaKXz @coreyfarrell at work until somewhat late tonight, please take the liberty of cherry picking that first patch and landing; if you see fit.

**Comment by JaKXz** [comment]
closing in favour of #960.

**Comment by JaKXz** [comment]
@bcoe want to wait until windows on Travis is a bit more stable to move over?

**Pull request closed without merging**
