### PR TITLE
added support for per file coverage checking

### PR DESCRIPTION
**Pull request by AmShaegar13**
Implements #468

### CODE REVIEW

**Comment by bcoe** [comment]
@AmShaegar13 clever, love it 👍

**Comment by bcoe** [comment]
@AmShaegar13 will try to get this landed this weekend.

**Comment by AmShaegar13** [comment]
@bcoe Any news?

**Comment by bcoe** [comment]
@AmShaegar13 great work, love how simple this implementation was.

**Comment by AmShaegar13** [comment]
Thanks!

**Comment by bcoe** [comment]
@AmShaegar13 this is now available if you run `npm i nyc@next` mind taking it for a spin and letting me know if everything works as expected on your projects?

**Comment by AmShaegar13** [comment]
@bcoe works like expected in version 11.1.0, thanks!

**Comment by bcoe** [comment]
@AmShaegar13 this awesome new feature is now live if you install the latest version of nyc.

**Pull request merged**
