### PR TITLE
Support turning off node_modules default exclude via flag

### PR DESCRIPTION
**Pull request by hershmire**
This PR is part of resolving [issue #898](https://github.com/istanbuljs/nyc/issues/898). The idea is to be able to turn off the default exclusion of `**/node_modules/**` for users that need/want to support local `node_modules`. As mentioned in that issue, the `negateExclude` (i.e. `!**/node_modules/**`) doesn't work for cases when you still want your exclusion list to still exclude matches within your local `node_modules` directory. 

Related PRs for solving the above issue:
- https://github.com/istanbuljs/istanbuljs/pull/213
- https://github.com/istanbuljs/babel-plugin-istanbul/pull/172

**NOTE:** this test-exclude PR (https://github.com/istanbuljs/istanbuljs/pull/213) will need to get merged and published before this is effective.

### CODE REVIEW

**Comment by hershmire** [comment]
@bcoe This issue I wrote up back in August might answer some of your questions – https://github.com/istanbuljs/nyc/issues/898.

**Comment by hershmire** [comment]
@bcoe Any update?

**Comment by JaKXz** [comment]
@hershmire I'm sorry for the late reply & if what I say next might be frustrating to you:

If the `node_modules` that are in those sub-projects/pages are actually local modules (that you hand rolled in place) and not `npm install`ed into those sub-projects/pages, why does the folder have to be called `node_modules`? CJS requires can work with relative paths so I'm not sure that adding all this cyclomatic complexity to `nyc`/`istanbul` is the right approach. As @coreyfarrell said in #898 there are more complex use cases with mono-repos that are becoming more common now to support, so unless this plays nice I don't see this being implemented TBPH. 

to anyone: please correct me if I'm wrong.

**Comment by bcoe** [comment]
@JaKXz @hershmire I would love to add better semantics for including `node_modules`, but I think we should do this work in the [test-exclude](https://github.com/istanbuljs/istanbuljs/tree/master/packages/test-exclude) module, rather than in nyc itself 👍 let's try to pick this work back up though.

**Comment by coreyfarrell** [comment]
@hershmire Sorry for the long delay on this, my intent is that this feature will be available in nyc 14.

@bcoe this feature is already added to `test-exclude` via istanbuljs/istanbuljs#213, now we just need to expose it to users via nyc.

@AndrewFinlay we will want to add the `--exclude-node-modules` option to `nyc instrument`.  I didn't add that to this change because I don't want to cause conflicts with #1007 which is nearly ready for merge.

**Pull request merged**
