### PR TITLE
chore(package): update spawn-wrap to 1.3.2

### PR DESCRIPTION
**Pull request by TheAlphaNerd**
This fixes the wrapping of custom node binaries

### CODE REVIEW

**Comment by bcoe** [comment]
@TheAlphaNerd nice, thanks for updating this.

**Comment by bcoe** [comment]
@TheAlphaNerd I will need to spin up a VM and dig into why this is breaking on Windows.

**Comment by bcoe** [comment]
@isaacs @TheAlphaNerd here's the bug:

https://github.com/tapjs/spawn-wrap/blob/master/index.js#L133

Should be `.test()` not `.match()` 👍

**Comment by TheAlphaNerd** [comment]
sent in a PR to spawn-wrap... will update this PR when it lands

**Pull request closed without merging**
