### PR TITLE
resolves #765 resolve custom cache directory to an absolute path

### LINKED ISSUE #765: Custom cache directory should be resolved to an absolute path
## Expected Behavior

I expect nyc to consistently use the same cache directory throughout the process. When a custom cache directory is specified as a relative path, and the working directory of the process changes, this assumption is violated.

The custom cache path needs to be resolved to an absolute path (using `path.resolve()`) before it's used.

## Observed Behavior

If a custom cache directory is specified as a relative path (such as in package.json), and the working directory of the process is changed by one of the tests, then the cache directory will be recreated in a new location for that portion of the test suite. This puts cache files in an unexpected location and defeats the purpose of having a cache.

If the cache directory is left unspecified, then nyc correctly resolves the value to an absolute path. It's the custom path that isn't being resolved.

See: https://github.com/istanbuljs/nyc/blob/master/index.js#L52

This line needs to be:

```js
this.cacheDirectory = path.resolve(config.cacheDir) || findCacheDir({name: 'nyc', cwd: this.cwd})
```

## Forensic Information

**Operating System:** Fedora 26 (Linux)
**Environment Information:**

Node: v8.9.3
npm: 5.5.1
yarn: 1.3.2
nyc: 11.4.1

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

**Comment by mojavelinux** [comment]
How's it look?

**Comment by mojavelinux** [comment]
@bcoe Anything else you want me to do?

**Comment by bcoe** [comment]
@mojavelinux 👍 I apologize for taking a long time to land this, I've been facing a family tragedy, and have just been starting to do a tiny bit of open-source work again. I'll get a candidate release of this out the door for you soon, so you can test things out.

**Comment by bcoe** [comment]
@mojavelinux try `npm i nyc@next` this update should have your changes.

**Comment by mojavelinux** [comment]
No need to apologize. I completely understand. My heartfelt condolences to you and your family, from your family in open source. :heart: Thank you for taking the time away from your family to review and merge this change.

**Comment by mojavelinux** [comment]
Fix confirmed!

**Comment by mojavelinux** [comment]
Thanks again!

While I now understand where nyc puts the cache by default, defining it explicitly in my package.json file makes me feel a lot more comfortable. I can now do that thanks to this fix:

```json
  "nyc": {
    "cache": true,
    "cacheDir": "node_modules/.cache/nyc"
  }
```

**Pull request merged**
