### PR TITLE
Add possibility to filter coveragemaps

### PR DESCRIPTION
**Pull request by schutm**
As dicussed in https://github.com/istanbuljs/istanbuljs/pull/24

I found some time to recreate the implementation of this using sourcemaps. The sourcemaps made it way easier and it looks nicer as well now!

To reiterate why I made this: I've a 'non-standard' setup, where I build my distribution-packages outside of the source folder. I do this because I write mainly ES6 code, and distribution-packages need to be plain old JavaScript. In addition because AVA is perfectly able to run ES6 tests, but not able to test ES6 modules I've to transpile my ES6 code (using rollup and babel/bublé) to plain JavaScript. The resulting transpiled file will also include all libraries being imported.

In addition you can use this feature to make more specific reports. Instrument once, and split your reporting over different folders, or outputs. E.g. in the mono-repo have a HTML-report per library.

### CODE REVIEW

**Comment by schutm** [comment]
Anybody know how I can recheck this PR in appveyor. It seems to report the wrong status.

**Comment by bcoe** [comment]
@schutm you can always just push an empty commit:

`git push --allow-empty -m "make annoying appveyor be less annoying"`

thanks for dusting this off.

**Comment by bcoe** [comment]
@schutm thanks for the contribution, sorry it took so long to land!

I recently stood up a community slack here, to try to better coordinate work around the OSS projects Ive been managing:

http://devtoolscommunity.herokuapp.com/

would love to have you join, and help prod me into getting a new release of nyc out the door.

**Comment by bcoe** [comment]
@schutm this is now released in `nyc@11.2.0` thanks for the contribution. [I've already been testing things out](https://github.com/nodejs/node/pull/15194), awesome work.

**Pull request merged**
