### PR TITLE
feat: upgrade the version of spawn-wrap for windows issue

### PR DESCRIPTION
**Pull request by popomore**
Relate https://github.com/tapjs/spawn-wrap/commit/fc98d38664c364cc55588e39de747aef03d767ea

### CODE REVIEW

**Comment by popomore** [comment]
cc @bcoe

**Comment by bcoe** [comment]
@popomore looks good to me 👍

**Comment by popomore** [comment]
Can you release a new version?

**Comment by bcoe** [comment]
@popomore please try `npm i nyc@next` and let me know if it works as expected.

**Pull request merged**
