### PR TITLE
feat: Option Plugins

### PR DESCRIPTION
**Pull request by wzalazar**
This PR introduces:

The ability to add more plugins for [@babel/parser](https://babeljs.io/docs/en/babel-parser) to istanbuljs instrumenter

related https://github.com/poetapp/node/pull/230 https://github.com/istanbuljs/istanbuljs/pull/205

### CODE REVIEW

**Comment by wzalazar** [comment]
The CI fails because I have problems with node version 6.15.1, the issue is with `LAZY_LOAD_COUNT`, if I change this line in local with node version 6.15.1 the command `npm test` is executed successfully

```
 // modules lazy-loaded when first file is instrumented.
-const LAZY_LOAD_COUNT = 266
+const LAZY_LOAD_COUNT = 269
```

I'm not sure how I can fix it, also I don't understand how my changes affect these tests

**Comment by JaKXz** [comment]
@wzalazar thank you for the contribution. Would you mind rebasing, I think we've made some changes recently that will better support this (in testing especially)

**Comment by wzalazar** [comment]
@JaKXz failed again, can you check out? I don't can reload the task

**Comment by coreyfarrell** [comment]
Looks like a travis-ci error installing node.js on Windows.  I restarted the job.

**Comment by JaKXz** [comment]
I'll leave this to @coreyfarrell or @bcoe to merge!

**Comment by coreyfarrell** [comment]
@wzalazar thank you for the contribution!

**Pull request merged**
